---
title: "A ggplot flipbook"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
library(palmerpenguins)
xaringanExtra::use_xaringan_extra(include = c("panelset", "tile_view", "share_again"))
```



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

```{r scatterplot, include=FALSE}
penguins %>% #BREAK
  ggplot() + #BREAK
  aes(x = flipper_length_mm) + #BREAK
  aes(y = bill_length_mm) + #BREAK  
  geom_point() + #BREAK
  aes(color = species) + #BREAK
  aes(shape = species) + #BREAK
  geom_point(size = 3, alpha = 0.6) + #BREAK
  geom_smooth(method = "lm", 
              se = FALSE, 
              aes(color = species)) + #BREAK
  theme_minimal() + #BREAK
  scale_color_manual(values = c("darkorange", "purple", "cyan4")) + #BREAK
  labs(title = "Penguin size, Palmer Station LTER") + #BREAK
  labs(subtitle = "Flipper length and body mass for Adelie, Chinstrap and Gentoo Penguins") + #BREAK
  labs(x = "Flipper length (mm)") + #BREAK
  labs(y = "Body mass (g)") + #BREAK
  labs(color = "Penguin species") + #BREAK
  labs(shape = "Penguin species") + #BREAK
  theme(legend.position = c(0.85, 0.15)) + #BREAK
  theme(legend.background = element_rect(fill = "white", color = NA)) + #BREAK
  theme(plot.title.position = "plot") #BREAK
```

---

`r chunk_reveal(chunk_name = "scatterplot", break_type = "user")`
