---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Reproducible Reporting with R Markdown"
subtitle: ""
summary: " "
authors: []
tags: []
categories: []
date:
lastmod: 2020-09-15T12:25:10-07:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: "Artwork by [@allison_horst](https://twitter.com/allison_horst)"
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
links:
- icon: film
  icon_pack: fas
  name: Slides
  url: /slides/09-slides.html
- icon: readme
  icon_pack: fab
  name: Cheat Sheet
  url: https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf
- icon: readme
  icon_pack: fab
  name: Reference Guide
  url: https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf
---

R Markdown is one of the most powerful tools at your disposal as a scientist -- particularly for communicating and sharing your work. For example, this entire website and all of the slides were created using R Markdown! Today we'll take a little deeper of a dive into what R Markdown is than what we covered in our initial introduction to R, and you will hopefully get a sense of the endless possibilities it affords you. 

***

### Slides

```{r echo=FALSE}
xaringanExtra::embed_xaringan(
  url = "/slides/09-slides.html",
  ratio = "16:9"
)
```

<br>

### Further Reading

:::book
1. [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)

2. [R Markdown for Scientists](https://rmd4sci.njtierney.com/)

3. Workshops on [introductory](https://rmd4medicine.netlify.app/) and [advanced](https://arm.rbind.io/) R Markdown by Alison Hill Yihuie Xie (two R Markdown legends `r emo::ji("star-struck")`)

4. [Tips for working with images and figures](http://zevross.com/blog/2017/06/19/tips-and-tricks-for-working-with-images-and-figures-in-r-markdown-documents/) in R Markdown by Zev Ross

5. [blogdown: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/)

6. [Overview of R Markdown](https://rmarkdown.rstudio.com/lesson-1.html) from RStudio
:::
